Repository Junhyung-Choi/Algorithm, pull requests merged in 2023-08, with the labels that each got.

#3 [정렬, 시뮬레이션] 세준세비(1524)
  풀이/Jihoon/done/[정렬, 시뮬레이션] 세준세비(1524).c
  풀이/Jihoon/todo/세준세비.py
Labels: EASY, BOJ, C

#1 [정렬, 시뮬레이션] 세준세비(1524)
  풀이/Junhyeong/done/BOJ/세준세비.py
  풀이/Junhyeong/todo/세준세비.py
Labels: Python, EASY, BOJ

#6 [정렬, 시뮬레이션] 세준세비(1524)
  풀이/Minseon/done/BOJ/세준세비.cpp
  풀이/Minseon/todo/세준세비.cpp
Labels: C++, NORMAL, BOJ

#5 [다익스트라] 지름길(1446)
  풀이/Eunsun/todo/done/[다익스트라]숨바꼭질(1697).py
  풀이/Eunsun/todo/done/[다익스트라]지름길(1446).py
  풀이/Eunsun/todo/세준세비.py
Labels: Python, NORMAL

#4 [시뮬레이션] 세준세비 (1524)
  풀이/Juhee/done/BOJ/세준세비.js
  풀이/Juhee/todo/세준세비.py
Labels: Javascript, EASY, BOJ

#11 [다익스트라]특정 거리의 도시찾기(18352)
  .gitignore
  풀이/Jihoon/done/[다익스트라]숨바꼭질.py
  풀이/Jihoon/done/[다익스트라]특정 거리의 도시 찾기.py
  풀이/Jihoon/done/a.out
  풀이/Jihoon/todo/[다익스트라]숨바꼭질.py
  풀이/Jihoon/todo/[다익스트라]지름길.py
Labels: Python, HARD, BOJ

#12 [다익스트라] 녹색옷을입은애가젤다지 (4485)
  .gitignore
  풀이/Junhyeong/todo/[다익스트라]녹색옷입은애가젤다지.py
Labels: Python, NORMAL, BOJ

#13 [다익스트라] 녹색 옷 입은 애가 젤다지? (4485)
  풀이/Minseon/done/BOJ/[다익스트라]녹색옷입은애가젤다지.cpp
  풀이/Minseon/todo/[다익스트라]녹색옷입은애가젤다지.py
Labels: C++, NORMAL, BOJ

#15 [다익스트라] - 지름길 (1446)
  풀이/Minhyeok/done/[다익스트라]지름길.js
Labels: Javascript, HARD, BOJ

#10 [정렬, 시뮬레이션] 세준세비(1524)
  풀이/Minhyeok/done/[다익스트라]지름길.js
  풀이/Minhyeok/done/세준세비.js
  풀이/Minhyeok/todo/[다익스트라]숨바꼭질.py
  풀이/Minhyeok/todo/[다익스트라]지름길.js
  풀이/Minhyeok/todo/세준세비.js
Labels: Javascript, EASY, BOJ
